GET http://localhost:1234/pokemon/ditto

##########

POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "level": 1,
  "hp": 100,
  "attack": 100,
  "defense": 100,
  "specialAttack": 100,
  "specialDefense": 100,
  "speed": 100
}